name: Deploy Nelami

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: SSH and prepare repositories
        run: |
          ssh ${{ secrets.USER_AT_SERVER }} <<'EOF'
          sudo su -

          # Load NVM
          export NVM_DIR="/root/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm use 22

          echo "Node: $(node -v)"
          echo "NPM : $(npm -v)"

          # Pull the latest Nelami app code
          cd /root/nelami

          if [ ! -d .git ]; then
            git init
            git remote add origin git@github.com:Hamzi-SE/nelami.git
          fi

          git fetch origin
          git reset --hard origin/main

          # Pull the latest configs code
          if [ ! -d /root/configs ]; then
            git clone git@github.com:Hamzi-SE/configs.git /root/configs
          else
            cd /root/configs
            git fetch origin
            git reset --hard origin/main
          fi

          # Copy env files
          mkdir -p /root/nelami/backend/config

          cp /root/configs/nelami-backend.env /root/nelami/backend/config/config.env
          cp /root/configs/nelami-frontend.env /root/nelami/frontend/.env

          exit
          EOF

      - name: SSH and deploy backend
        run: |
          ssh ${{ secrets.USER_AT_SERVER }} <<'EOF'
          sudo su -

          # Load NVM
          export NVM_DIR="/root/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm use 22

          echo "Node: $(node -v)"
          echo "NPM : $(npm -v)"

          cd /root/nelami/backend

          npm ci

          pm2 delete nelami_server || true
          pm2 start npm --name "nelami_server" -- start

          exit
          EOF

      - name: SSH and deploy frontend
        run: |
          ssh ${{ secrets.USER_AT_SERVER }} <<'EOF'
          sudo su -

          # Load NVM
          export NVM_DIR="/root/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm use 22

          echo "Node: $(node -v)"
          echo "NPM : $(npm -v)"
          echo "Arch: $(uname -m)"

          cd /root/nelami/frontend

          rm -rf node_modules
          rm -f package-lock.json

          npm cache clean --force

          npm run build

          exit
          EOF
